# Generated by Django 3.1.2 on 2020-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokey',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
