# Generated by Django 3.1.2 on 2020-12-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
